### ISSUE TITLE
[F-Droid] Releasing the bugfixed version.

### ISSUE THREAD

**Issue by lss4** [NHellFire/KernelAdiutor#2]
As of now the F-Droid version is still the one with the known bugs (broken Apply on Boot and Material Icon). I'm not sure when the fixed version will be released there since the problem has been corrected as of the latest commits.

**Comment by dimqua** [comment]
It's [already released](https://github.com/NHellFire/KernelAdiutor/releases/tag/v0.9.73.1.1), but F-Droid does not have this version yet. See: https://gitlab.com/fdroid/fdroiddata/issues/962

**Comment by lss4** [comment]
Yeah, I'm aware of it... just hope the new version can be actually built and signed by F-Droid so one can update it... is there some manual process needed for F-Droid to build the next version?

EDIT: Yeah, it seems the app version code needs to be changed to reflect the new version number in order to get F-Droid build and sign the fixed version.

**Comment by lss4** [comment]
@dimqua The issue at F-Droid GitLab was closed due to the v0.9.73.1.1 release did not change the version code in build.gradle (probably to avoid delta from upstream). F-Droid cannot build the new release if the version code is the same as the previous release.

**Comment by NHellFire** [comment]
I'd already updated the versionCode, but the tag didn't push. Fixed now and commented on the fdroid issue.

**Comment by lss4** [comment]
The new version's now released on F-Droid and tested working. :-)
Closing the issue.
